version: '3.1'
services:
  app:
    image: seeder
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - database
  database:
    image: mariadb
    environment:
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
      MARIADB_ROOT_PASSWORD: "${MARIADB_PASSWORD}"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "13306:3306"
volumes:
  db-data: